stages:
  - build

default:
  cache:
    - key:
        files:
          - gradle/wrapper/gradle-wrapper.properties
      paths:
        - .gradle/wrapper
        - .gradle/notifications
    - key: "$CI_COMMIT_REF_SLUG"
      paths:
        - .gradle/caches
        - .gradle/configuration-cache

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  image: registry.gitlab.com/dagadeta-public/dind-jdk-image@sha256:7b5cb0ab427591b4b3059ec71ab6abb73a9d424eb091ea40ac356b293264df9e
  services:
    - docker:29-dind
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_TLS_CERTDIR: ""
  rules:
    - if: '$CI_PROJECT_PATH == "dagadeta-public/discord-bot"'
      when: always
    - when: never
  script:
    - ./gradlew test integTest e2eTest build koverLog koverXmlReport
  coverage: '/Code Coverage: \d+\.\d+%/' # Regex to extract coverage from koverLog
  artifacts:
    when: always
    paths:
      - build/reports
      - app/build/reports
    reports:
      junit: "app/build/test-results/**/TEST-*.xml"
      coverage_report:
        coverage_format: jacoco
        path: "app/build/reports/kover/report.xml"
    expire_in: 1 week
