stages:
  - build
  - test

default:
  image: gradle:9.3-jdk17
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .gradle/wrapper
      - .gradle/caches

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

build:
  stage: build
  rules:
    - when: always
  script:
    - ./gradlew build koverLog -x app:integTest -x app:e2eTest
  artifacts:
    paths:
      - build/
      - "**/build/"

integration_tests:
  stage: test
  image: docker:29
  services:
    - docker:29-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  rules:
    - when: always
  before_script:
    - apk add --no-cache openjdk17-jdk bash
  script:
    - ./gradlew app:integTest koverLog -x app:e2eTest
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/**/TEST-*.xml"

e2e_tests:
  stage: test
  image: docker:29
  services:
    - docker:29-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  rules:
    - if: '$CI_PROJECT_PATH == "dagadeta-public/discord-bot"'
      when: on_success
    - when: never
  before_script:
    - apk add --no-cache openjdk17-jdk bash
  script:
    - ./gradlew app:e2eTest koverXmlReport koverLog
  coverage: '/Code Coverage: \d+\.\d+%/' # Regex to extract coverage from koverLog
  artifacts:
    reports:
      junit: "**/build/test-results/**/TEST-*.xml"
      coverage_report:
        coverage_format: jacoco
        path: "**/build/reports/kover/report.xml"
