stages:
  - build
  - test
  - secret-detection

variables:
  SECRET_DETECTION_ENABLED: 'true'

.gradle-cache:
  variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  cache:
    - key:
        files:
          - gradle/wrapper/gradle-wrapper.properties
      paths:
        - .gradle/wrapper
        - .gradle/notifications
    - key: "$CI_COMMIT_REF_SLUG"
      paths:
        - .gradle/caches
        - .gradle/configuration-cache

build:
  stage: build
  extends: .gradle-cache
  image: registry.gitlab.com/dagadeta-public/dind-jdk-image@sha256:e78e394e1bdf2b9ef62ae5c48bd4b63d72e7cd9245dda3cb68d1a0d3ed76845f
  services:
    - docker:29-dind
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_TLS_CERTDIR: ""
  rules:
    - if: '$CI_PROJECT_PATH == "dagadeta-public/discord-bot"'
      when: always
    - when: never
  script:
    - ./gradlew test integTest e2eTest build koverLog koverXmlReport
  coverage: '/Code Coverage: \d+\.\d+%/' # Regex to extract coverage from koverLog
  artifacts:
    when: always
    paths:
      - build/reports
      - app/build/reports
    reports:
      junit: "app/build/test-results/**/TEST-*.xml"
      coverage_report:
        coverage_format: jacoco
        path: "app/build/reports/kover/report.xml"
    expire_in: 1 week

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
secret_detection:
  stage: secret-detection
