services:
  db:
    image: postgres:18.4
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql:Z
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: discordbot
