services:
  db:
    image: postgres:16.9
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: discordbot