/*
 * This source file was generated by the Gradle 'init' task
 */
package de.dagadeta.schlauerbot

import net.dv8tion.jda.api.JDABuilder
import net.dv8tion.jda.api.requests.GatewayIntent
import java.io.File
import java.util.*


class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val props = Properties()
    val inputStream = File("config.properties").inputStream()
    inputStream.use {
        props.load(inputStream)
    }

    val wordChainGame = WordChainGame(props.getProperty("wordChainGame.channelId").toLong())
    val api = JDABuilder
        .createLight(props.getProperty("bot.token"), GatewayIntent.GUILD_MESSAGES, GatewayIntent.MESSAGE_CONTENT, GatewayIntent.GUILD_MEMBERS)
        .addEventListeners(
            DingDongListener(),
            wordChainGame,
            WordChainCommandListener(wordChainGame)
        )
        .build()

    api.awaitReady()

    configureDingDongCommands(api)
    configureWordChainCommands(api)

    val logging = Logging(api, props.getProperty("logging.guildId").toLong(), props.getProperty("logging.channelId").toLong())

    logging.log("Bot started")
}