bot-auth.token: ${AUTH_TOKEN}

logging:
  guild-id: ${GUILD_ID}
  channel-id: ${LOGGING_CHANNEL_ID}

word-chain-game:
  channel-id: ${WORDCHAINGAME_CHANNEL_ID}
  language: en
  check-word-existence: true

ding-dong:
  channel-id: ${DINGDONG_CHANNEL_ID}
